//! Frames of the overlap timer as the game's own code ran them: per frame
//! the inputs that differ from the default (overlapping, no group talk,
//! state Idle, a cancel that succeeds), the result, the timer bits after the
//! frame, and whether the cancel was attempted. Generated; do not edit by
//! hand.

use super::overlap_frame;

struct Row {
    overlap: bool,
    group_talk: bool,
    state: i32,
    cancel_ok: bool,
    ret: bool,
    timer: u32,
    attempted: bool,
}

struct Case {
    name: &'static str,
    dt: u32,
    limit: u32,
    rows: &'static [Row],
}

const CASES: &[Case] = &[
    Case {
        name: "steady 1/60",
        dt: 0x3c888889,
        limit: 0x40000000,
        rows: &[
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3c888889, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3d088889, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3d4cccce, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3d888889, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3daaaaab, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3dcccccd, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3deeeeef, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e088889, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e19999a, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e2aaaab, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e3bbbbc, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e4ccccd, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e5dddde, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e6eeeef, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e800000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e888889, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e911112, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e99999b, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ea22224, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3eaaaaad, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3eb33336, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ebbbbbf, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ec44448, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3eccccd1, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ed5555a, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3edddde3, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ee6666c, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3eeeeef5, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ef7777e, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000003, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f044447, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f08888b, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f0ccccf, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f111113, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f155557, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f19999b, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f1ddddf, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f222223, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f266667, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f2aaaab, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f2eeeef, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f333333, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f377777, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f3bbbbb, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f3fffff, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f444443, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f488887, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f4ccccb, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f51110f, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f555553, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f599997, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f5ddddb, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f62221f, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f666663, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f6aaaa7, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f6eeeeb, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f73332f, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f777773, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f7bbbb7, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f7ffffb, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f822220, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f844442, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f866664, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f888886, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f8aaaa8, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f8cccca, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f8eeeec, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f91110e, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f933330, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f955552, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f977774, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f999996, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f9bbbb8, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f9dddda, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f9ffffc, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fa2221e, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fa44440, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fa66662, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fa88884, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3faaaaa6, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3facccc8, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3faeeeea, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fb1110c, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fb3332e, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fb55550, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fb77772, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fb99994, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fbbbbb6, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fbdddd8, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fbffffa, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc2221c, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc4443e, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc66660, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc88882, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fcaaaa4, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fccccc6, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fceeee8, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fd1110a, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fd3332c, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fd5554e, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fd77770, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fd99992, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fdbbbb4, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fddddd6, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fdffff8, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fe2221a, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fe4443c, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fe6665e, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fe88880, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3feaaaa2, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fecccc4, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3feeeee6, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ff11108, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ff3332a, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ff5554c, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ff7776e, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ff99990, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ffbbbb2, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ffdddd4, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ffffff6, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x4001110c, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: true, timer: 0x00000000, attempted: true },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3c888889, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3d088889, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3d4cccce, attempted: false },
        ],
    },
    Case {
        name: "steady 1/30",
        dt: 0x3d088889,
        limit: 0x40000000,
        rows: &[
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3d088889, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3d888889, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3dccccce, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e088889, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e2aaaab, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e4ccccd, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e6eeeef, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e888889, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e99999a, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3eaaaaab, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ebbbbbc, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ecccccd, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3eddddde, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3eeeeeef, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f088889, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f111112, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f19999b, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f222224, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f2aaaad, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f333336, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f3bbbbf, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f444448, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f4cccd1, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f55555a, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f5ddde3, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f66666c, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f6eeef5, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f77777e, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f800003, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f844447, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f88888b, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f8ccccf, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f911113, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f955557, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f99999b, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f9ddddf, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fa22223, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fa66667, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3faaaaab, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3faeeeef, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fb33333, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fb77777, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fbbbbbb, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fbfffff, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc44443, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc88887, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fcccccb, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fd1110f, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fd55553, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fd99997, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fdddddb, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fe2221f, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fe66663, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3feaaaa7, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3feeeeeb, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ff3332f, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ff77773, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ffbbbb7, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ffffffb, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x40022220, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: true, timer: 0x00000000, attempted: true },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3d088889, attempted: false },
        ],
    },
    Case {
        name: "steady 0.5",
        dt: 0x3f000000,
        limit: 0x40000000,
        rows: &[
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f800000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc00000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x40000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: true, timer: 0x00000000, attempted: true },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
        ],
    },
    Case {
        name: "steady 0.25",
        dt: 0x3e800000,
        limit: 0x40000000,
        rows: &[
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e800000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f400000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f800000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fa00000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc00000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fe00000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x40000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: true, timer: 0x00000000, attempted: true },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e800000, attempted: false },
        ],
    },
    Case {
        name: "steady 0.1",
        dt: 0x3dcccccd,
        limit: 0x40000000,
        rows: &[
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3dcccccd, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e4ccccd, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e99999a, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ecccccd, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f19999a, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f333334, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f4cccce, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f666668, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f800001, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f8cccce, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f99999b, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fa66668, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fb33335, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc00002, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fcccccf, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fd9999c, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fe66669, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3ff33336, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x40000001, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: true, timer: 0x00000000, attempted: true },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3dcccccd, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e4ccccd, attempted: false },
        ],
    },
    Case {
        name: "limit 1.3 dt 0.25",
        dt: 0x3e800000,
        limit: 0x3fa66666,
        rows: &[
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e800000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f400000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f800000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fa00000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc00000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: true, timer: 0x00000000, attempted: true },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3e800000, attempted: false },
        ],
    },
    Case {
        name: "overlap off at frame 3, dt 0.5",
        dt: 0x3f000000,
        limit: 0x40000000,
        rows: &[
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f800000, attempted: false },
            Row { overlap: false, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x00000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f800000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc00000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x40000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: true, timer: 0x00000000, attempted: true },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
        ],
    },
    Case {
        name: "group talk at frame 4, dt 0.5",
        dt: 0x3f000000,
        limit: 0x40000000,
        rows: &[
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f800000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc00000, attempted: false },
            Row { overlap: true, group_talk: true, state: 0, cancel_ok: true, ret: false, timer: 0x00000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f800000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc00000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x40000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: true, timer: 0x00000000, attempted: true },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
        ],
    },
    Case {
        name: "state Talk (4) at the limit, then Idle",
        dt: 0x3f000000,
        limit: 0x40000000,
        rows: &[
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f800000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc00000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x40000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 4, cancel_ok: true, ret: false, timer: 0x00000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f800000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc00000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x40000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: true, timer: 0x00000000, attempted: true },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
        ],
    },
    Case {
        name: "state 21 and -1 at the limit (unsigned > 20)",
        dt: 0x3f000000,
        limit: 0x40000000,
        rows: &[
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f800000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc00000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x40000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 21, cancel_ok: true, ret: false, timer: 0x00000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f800000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc00000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x40000000, attempted: false },
            Row { overlap: true, group_talk: false, state: -1, cancel_ok: true, ret: false, timer: 0x00000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
        ],
    },
    Case {
        name: "states 1, 7, 20 at the limit",
        dt: 0x3f000000,
        limit: 0x40000000,
        rows: &[
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f800000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc00000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x40000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 1, cancel_ok: true, ret: true, timer: 0x00000000, attempted: true },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f800000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc00000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x40000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 7, cancel_ok: true, ret: true, timer: 0x00000000, attempted: true },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f800000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc00000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x40000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 20, cancel_ok: true, ret: true, timer: 0x00000000, attempted: true },
        ],
    },
    Case {
        name: "state 2 (Rotate) at the limit",
        dt: 0x3f000000,
        limit: 0x40000000,
        rows: &[
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f800000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc00000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x40000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 2, cancel_ok: true, ret: false, timer: 0x00000000, attempted: false },
        ],
    },
    Case {
        name: "cancel refused twice then accepted",
        dt: 0x3f000000,
        limit: 0x40000000,
        rows: &[
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3f800000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x3fc00000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: false, timer: 0x40000000, attempted: false },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: false, ret: false, timer: 0x40000000, attempted: true },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: false, ret: false, timer: 0x40000000, attempted: true },
            Row { overlap: true, group_talk: false, state: 0, cancel_ok: true, ret: true, timer: 0x00000000, attempted: true },
        ],
    },
];

#[test]
fn overlap_timer_matches_the_game() {
    for case in CASES {
        let mut timer = 0.0_f32;
        for (index, row) in case.rows.iter().enumerate() {
            let frame = index + 1;
            let attempted = overlap_frame(
                &mut timer,
                f32::from_bits(case.dt),
                f32::from_bits(case.limit),
                row.overlap,
                row.group_talk,
                row.state as u32,
            );
            // The caller: a cancel that reports true resets the timer and
            // returns true; a refused one keeps the timer.
            let ret = attempted && row.cancel_ok;
            if ret {
                timer = 0.0;
            }
            assert_eq!(attempted, row.attempted, "{} frame {frame}: attempt", case.name);
            assert_eq!(ret, row.ret, "{} frame {frame}: result", case.name);
            assert_eq!(timer.to_bits(), row.timer, "{} frame {frame}: timer", case.name);
        }
    }
}

/// At 1/60 s the cancel fires on frame 122, not before.
#[test]
fn fires_at_the_limit_not_before() {
    let mut timer = 0.0_f32;
    let dt = f32::from_bits(0x3c888889);
    let fired: Vec<usize> = (1..=200)
        .filter(|_| overlap_frame(&mut timer, dt, 2.0, true, false, 0))
        .take(1)
        .collect();
    assert_eq!(fired, [122]);
}
